### ISSUE TITLE
Have a way to "temporarily close" places

### ISSUE THREAD

**Issue by jpmurray** [Solution-locale/solutionlocale.ca#12]
As more drastic lockdown action are happening, some business choose to close for the time being, and some of them where already in the directory. We have to add an option so moderator can temporarily close / hide said businesses.

**Comment by rachids** [comment]
I added a way to filter any model using [this article](https://blog.jgrossi.com/2018/queryfilter-a-model-filtering-concept/) that way you can use the filtering power in the public pages also which I think would be better ;)

Feel free to comment my PR.
Wasn't sure where you wanted the "open/close" form, so I made a view to list all places.

Sur ce, bon confinement! :)

**Comment by jpmurray** [comment]
Merged in #26
