### ISSUE TITLE
Adds a filter to get all places that do postal delivery

### ISSUE THREAD

**Issue by jpmurray** [Solution-locale/solutionlocale.ca#19]
Would call it `distribution postale`.

**Comment by geoffm** [comment]
The filter could be applicable to all delivery options.

**Comment by jpmurray** [comment]
Could be.!But our immediate need with this is to enable a specific page that does not cover a region in particular. So that people all round the province can seek out business that can send them something wherever they are.

**Comment by jpmurray** [comment]
We have a filter that enables to get only listings that offers _dlivery_.
