### ISSUE TITLE
Validation of PlaceRequest seems to return same message two time

### ISSUE THREAD

**Issue by jpmurray** [Solution-locale/solutionlocale.ca#29]
We'll add some variety to it.

![Capture d’écran 2020-03-27 à 08 40 42](https://user-images.githubusercontent.com/1550428/77763130-f9259980-7010-11ea-9fe8-70ac4e4b3dc7.png)

**Comment by PierrePaul** [comment]
The error doesn't show up anymore on master and in production. Has this been fixed?

**Comment by jpmurray** [comment]
@jpmurray I've only had one report and one instance of the error myself, and couldn't reproduct it myself. If you couldn't get it yourself either, I'll definitely be closing this!

**Comment by jpmurray** [comment]
Never seen it again in the wild. Probably fixed per proxy with another issue / commit. Closing.
