### ISSUE TITLE
Add parent relationship to categories

### ISSUE THREAD

**Issue by poliquinp** [Solution-locale/solutionlocale.ca#34]
Based on the list of new categories, add a parent relationship capability to categories.

**Comment by jpmurray** [comment]
Might already be in your pipeline, but I think we might have to plan in advance that we _might_ have multiple child categories.

**Comment by poliquinp** [comment]
> Might already be in your pipeline, but I think we might have to plan in advance that we _might_ have multiple child categories.

Task is on hold at the moment on our side. But our main idea was to create a "parent ID" where 0 is top level so we could easily do multi-level.

**Comment by jpmurray** [comment]
That's what I was seeing too! 👍

**Comment by jpmurray** [comment]
For the records: added in PR #43
