### ISSUE TITLE
Prevent spam in public submissions

### ISSUE THREAD

**Issue by jpmurray** [Solution-locale/solutionlocale.ca#8]
For now, we moderate, and don't see many spam but we probably should be ahead of the problem. [Honetpot package](https://github.com/spatie/laravel-honeypot) or Google's captcha ?

**Comment by jpmurray** [comment]
Used spatie's package. If not enough, we'll move to Google Recaptcha.

**Comment by poliquinp** [comment]
Just keep an eye on this if we need to install an Honeypot or a Google Recaptcha in a near future if spam starts to flood the form.
